config/routes.rb
Rails.application.routes.draw do
  root to: 'main_page#index', :controler => "main_page"
  
  devise_for :users
  
  scope "/admin" do
    resources :users, :controller => "users"  # MUST BE under 'devise_for :users'! It lets CRUD opera
  end

  resources :tasks
  resources :contexts
  resources :projects
  resources :project_categories
  resources :project_log_entries

  get 'tasks/:id/toggle_done' => 'tasks#toggle_done'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  belongs_to :project
  belongs_to :context

  #validates :name, :presence => true #spike

  extend SoftDeletableStatic
  include SoftDeletable
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #load_and_authorize_resource
  before_action :set_task_id
  before_action :set_task_service
  before_action :set_task, only: [:show, :edit]
  before_action :get_active_contexts, only: [:new, :edit]
  before_action :get_active_projects, only: [:new, :edit]

  def index
    @tasks = @task_service.get_active_tasks_of(current_user)
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def toggle_done
    if @task_service.toggle_done(@task_id, current_user)
      render :json => {:error => 0, :success => 1}
    else
      render :status => 500
    end
  end

  def create
    task_form = TaskForm.new(task_params)
    respond_to do |format|
      if @task_service.create(task_form, current_user)
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    task_form = TaskForm.new(task_params)
    respond_to do |format|
      if @task_service.update(@task_id, task_form, current_user)
        format.html { redirect_to tasks_url, notice: 'Task was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    ###Soft delete:
    @task_service.soft_delete(@task_id, current_user)
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.

  def set_task_service
    @task_service = TaskService.new
  end

  def set_task_id
    @task_id = params[:id]
  end

  def set_task
    @task = @task_service.get_task_by_id(@task_id, current_user)
    raise ActionController::RoutingError.new('Given Task is null') if @task.nil?
  end

  def get_active_contexts
    @active_contexts = current_user.contexts.active
  end

  def get_active_projects
    @active_projects = current_user.projects.active
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:name, :done, :deadline, :time_needed, :project_id, :context_id, :time_needed, :postponed_to)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for @task, html: { class: "form form-horizontal task" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@task[:name])
  .form-group
    = f.label :deadline, class: 'control-label'
    .controls
      = f.text_field :deadline, class: 'form-control'
    = error_span(@task[:deadline])
  .form-group
    = f.label :done, class: 'control-label'
    .controls
      = f.check_box :done, class: 'form-control'
    = error_span(@task[:done])
  .form-group
    = f.label :project_id, class: 'control-label'
    .controls
      = f.collection_select :project_id, @active_projects, :id, :name, {:include_blank => "No value", :required => true }
    = error_span(@task[:project_id])
  .form-group
    = f.label :time_needed, class: 'control-label'
    .controls
      = f.text_field :time_needed, class: 'form-control'
    = error_span(@task[:time_needed])
  .form-group
    = f.label :context_id, class: 'control-label'
    .controls
      = f.collection_select :context_id, @active_contexts, :id, :name, {:include_blank => "No value"}
    = error_span(@task[:context_id])

  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), tasks_path, :class => 'btn btn-default'

app/views/tasks/edit.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tasks/index.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped.tasks-table
  %thead
    %tr
      %th= model_class.human_attribute_name(:done)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:deadline)
      %th= model_class.human_attribute_name(:project)
      %th= model_class.human_attribute_name(:time_needed)
      %th= model_class.human_attribute_name(:context)
      %th= model_class.human_attribute_name(:postponed_to)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @tasks.each do |task|
      %tr.task-row{:class => ('success done' if task.done)}
        %td.done-check
          %a{:href => "#", :data => {'task-id' => task.id, 'task-done' => task.done.to_s } }
            -if task.done == true
              %span{:class => "glyphicon glyphicon-ok", 'aria-hidden' => "true"}
            -else
              %span{:class => "glyphicon glyphicon-screenshot", 'aria-hidden' => "true"}
        %td= link_to task.name, task_path(task)
        %td.datetime= task.deadline.datetime_without_seconds if task.deadline.nil? == false
        %td= link_to(task.project.name, project_path(task.project)) if task.project.nil? == false
        %td= task.time_needed
        %td
          -if task.context.nil? == false
            %a.context-label{style: "background-color: #{task.context.color}", :href => context_path(task.context) }
              %span{class: "glyphicon glyphicon-#{task.context.icon}"}
              = task.context.name
        %td.datetime= task.postponed_to.datetime_without_seconds if task.postponed_to.nil? == false
        %td.datetime= task.created_at.datetime_without_seconds
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(task), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(task), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_task_path, :class => 'btn btn-primary'

app/views/tasks/new.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tasks/show.html.haml
- model_class = Task
.page-header
  %h1
    = @task.name
%p
  %strong= model_class.human_attribute_name(:deadline) + ':'
  %br
  = @task.deadline.datetime_without_seconds if @task.deadline
%p
  %strong= model_class.human_attribute_name(:project) + ':'
  %br
  = link_to(@task.project.name, project_path(@task.project)) if @task.project.nil? == false
%p
  %strong= model_class.human_attribute_name(:time_needed) + ':'
  %br
  = @task.time_needed
%p
  %strong= model_class.human_attribute_name(:done) + ':'
  %br
  = @task.done
%p
  %strong= model_class.human_attribute_name(:postponed_to) + ':'
  %br
  = @task.postponed_to.datetime_without_seconds if @task.postponed_to
%p
  %strong= model_class.human_attribute_name(:context) + ':'
  %br
  = link_to(@task.context.name, context_path(@task.context)) if @task.context.nil? == false
%p
  %strong= model_class.human_attribute_name(:created_at) + ':'
  %br
  = @task.created_at.datetime_without_seconds

= link_to t('.back', :default => t("helpers.links.back")), tasks_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(@task), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(@task), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'