config/routes.rb
Rails.application.routes.draw do
  root to: 'main_page#index', :controler => "main_page"
  
  devise_for :users
  
  scope "/admin" do
    resources :users, :controller => "users"  # MUST BE under 'devise_for :users'! It lets CRUD opera
  end

  resources :tasks
  resources :contexts
  resources :projects
  resources :project_categories
  resources :project_log_entries

  get 'tasks/:id/toggle_done' => 'tasks#toggle_done'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to  :users

  has_many    :tasks
  belongs_to  :project_category
  has_many    :project_log_entries

  #validate :name, :presence => true

  extend SoftDeletableStatic
  include SoftDeletable
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #load_and_authorize_resource
  before_action :set_project_id
  before_action :set_project_service
  before_action :set_project, only: [:show, :edit]
  before_action :get_active_project_categories, only: [:new, :edit]

  def index
    @projects = @project_service.get_active_projects_of(current_user)
  end

  def show
    @project_log_entries = @project_service.get_history(@project_id)
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    project_form = ProjectForm.new(project_params)
    respond_to do |format|
      project = @project_service.create(project_form, current_user)
      if project
        format.html { redirect_to project_url(project.id), notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    project_form = ProjectForm.new(project_params)
    respond_to do |format|
      if @project_service.update(@project_id, project_form, current_user)
        format.html { redirect_to project_url(@project_id), notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    ###Soft delete:
    @project_service.soft_delete(@project_id, current_user)
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.

  def set_project_service
    @project_service = ProjectService.new
  end

  def set_project_id
    @project_id = params[:id]
  end

  def set_project
    @project = @project_service.get_project_by_id(@project_id, current_user)
    raise ActionController::RoutingError.new('Given Project is null') if @project.nil?
  end

  def get_active_project_categories
    @active_project_categories = current_user.project_categories.active
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :deadline, :project_category_id, :notes)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project, html: { class: "form form-horizontal project" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@project[:name])
  .form-group
    = f.label :deadline, class: 'control-label'
    .controls
      = f.text_field :deadline, class: 'form-control'
    = error_span(@project[:deadline])
  .form-group
    = f.label :project_category_id, class: 'control-label'
    .controls
      = f.collection_select :project_category_id, @active_project_categories, :id, :name, {:include_blank => "No value", :required => true}
    = error_span(@project[:project_category_id])
  .form-group
    = f.label :notes, class: 'control-label'
    .controls
      = f.text_area :notes, class: 'form-control'
    = error_span(@project[:notes])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), projects_path, :class => 'btn btn-default'

app/views/projects/edit.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/projects/index.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:deadline)
      %th= model_class.human_attribute_name(:project_category)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @projects.each do |project|
      %tr
        %td= link_to project.name, project_path(project)
        %td= project.deadline.datetime_without_seconds if project.deadline.nil? == false
        %td= link_to(project.project_category.name, project_category_path(project.project_category)) if project.project_category.nil? == false
        %td= project.created_at.datetime_without_seconds
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(project), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_project_path, :class => 'btn btn-primary'

app/views/projects/new.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/projects/show.html.haml
- model_class = Project
.page-header
  %h1
    .label.label-default=t '.title', :default => model_class.model_name.human.titleize
    = @project.name


%p
  %strong= model_class.human_attribute_name(:deadline) + ':'
  %br
  = @project.deadline.datetime_without_seconds if @project.deadline
%p
  %strong= model_class.human_attribute_name(:created_at) + ':'
  %br
  = @project.created_at.datetime_without_seconds
%p
  %strong= model_class.human_attribute_name(:project_category) + ':'
  %br
  = link_to(@project.project_category.name, project_category_path(@project.project_category)) if @project.project_category.nil? == false
%p
  %strong= model_class.human_attribute_name(:notes) + ':'
  %br
  = @project.notes


= link_to t('.back', :default => t("helpers.links.back")), projects_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(@project), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(@project), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'


-### render tasks:
- sub_model_class = Task

.panel.panel-default
  .panel-heading
    %h3.panel-title=t '.title', :default => sub_model_class.model_name.human.pluralize.titleize
  .panel-body
    %table.table.table-striped
      %thead
        %tr
          %th= model_class.human_attribute_name(:done)
          %th= model_class.human_attribute_name(:name)
          %th= model_class.human_attribute_name(:deadline)
          %th= model_class.human_attribute_name(:time_needed)
          %th= model_class.human_attribute_name(:context)
          %th= model_class.human_attribute_name(:postponed_to)
          %th= model_class.human_attribute_name(:created_at)
          %th=t '.actions', :default => t("helpers.actions")
      %tbody
        - @project.tasks.order(:done).order(:deadline).each do |task|
          %tr.task-row{:class => ('success done' if task.done)}
            %td.done-check
              %a{:href => "#", :data => {'task-id' => task.id, 'task-done' => task.done.to_s } }
                -if task.done == true
                  %span{:class => "glyphicon glyphicon-ok"}
                -else
                  %span{:class => "glyphicon glyphicon-screenshot"}
            %td= link_to task.name, task_path(task)
            %td= task.deadline
            %td= task.time_needed
            %td
              -if task.context.nil? == false
                -if task.done == false
                  %a.context-label{style: "background-color: #{task.context.color}", :href => context_path(task.context) }
                    %span{class: "glyphicon glyphicon-#{task.context.icon}"}
                    = task.context.name
                - else
                  %a.context-label{:href => context_path(task.context) }
                    %span{class: "glyphicon glyphicon-#{task.context.icon}"}
                    = task.context.name
            %td= task.postponed_to.datetime_without_seconds if task.postponed_to.nil? == false
            %td= task.created_at.datetime_without_seconds
            %td
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(task), :class => 'btn btn-default btn-xs'
              = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(task), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

    = link_to t('.new', :default => t("helpers.links.new")), new_task_path, :class => 'btn btn-primary'

- other_sub_model_class = ProjectLogEntry
.panel.panel-default
  .panel-heading
    %h3.panel-title=t '.title', :default => "Activity"
  .panel-body{:style => 'font-size: 8px;' }
    %table.table.table-striped
      %thead
        %tr
          %th= other_sub_model_class.human_attribute_name(:user_id)
          %th= other_sub_model_class.human_attribute_name(:activity_type)
          %th= other_sub_model_class.human_attribute_name(:previous_value)
          %th= other_sub_model_class.human_attribute_name(:new_value)
          %th= "When"
      %tbody
        - @project_log_entries.each do |project_log_entry|
          %tr
            %td= project_log_entry.user.email
            %td= project_log_entry.activity_type.humanize
            %td= project_log_entry.previous_value
            %td= project_log_entry.new_value
            %td= project_log_entry.created_at.datetime_without_seconds