config/routes.rb
Rails.application.routes.draw do
  root to: 'main_page#index', :controler => "main_page"
  
  devise_for :users
  
  scope "/admin" do
    resources :users, :controller => "users"  # MUST BE under 'devise_for :users'! It lets CRUD opera
  end

  resources :tasks
  resources :contexts
  resources :projects
  resources :project_categories
  resources :project_log_entries

  get 'tasks/:id/toggle_done' => 'tasks#toggle_done'

end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
  belongs_to :users

  has_many :projects

  #validate :name, :presence => true

  extend SoftDeletableStatic
  include SoftDeletable
end

app/controllers/project_categories_controller.rb
class ProjectCategoriesController < ApplicationController
  #load_and_authorize_resource
  before_action :set_project_category_id
  before_action :set_project_category_service
  before_action :set_project_category, only: [:show, :edit]
  before_action :get_active_contexts, only: [:new, :edit]
  before_action :get_active_projects, only: [:new, :edit]

  def index
    @project_categories = @project_category_service.get_active_project_categories_of(current_user)
  end

  def show
  end

  def new
    @project_category = ProjectCategory.new
  end

  def edit
  end

  def toggle_done
    if @project_category_service.toggle_done(@project_category_id, current_user)
      render :json => {:error => 0, :success => 1}
    else
      render :status => 500
    end
  end

  def create
    project_category_form = ProjectCategoryForm.new(project_category_params)
    respond_to do |format|
      if @project_category_service.create(project_category_form, current_user)
        format.html { redirect_to project_categories_url, notice: 'ProjectCategory was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    project_category_form = ProjectCategoryForm.new(project_category_params)
    respond_to do |format|
      if @project_category_service.update(@project_category_id, project_category_form, current_user)
        format.html { redirect_to project_categories_url, notice: 'ProjectCategory was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    ###Soft delete:
    @project_category_service.soft_delete(@project_category_id, current_user)
    respond_to do |format|
      format.html { redirect_to project_categories_url, notice: 'ProjectCategory was successfully destroyed.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def set_project_category_service
    @project_category_service = ProjectCategoryService.new
  end

  def set_project_category_id
    @project_category_id = params[:id]
  end

  def set_project_category
    @project_category = @project_category_service.get_project_category_by_id(@project_category_id, current_user)
    raise ActionController::RoutingError.new('Given ProjectCategory is null') if @project_category.nil?
  end

  def get_active_contexts
    @active_contexts = current_user.contexts.active
  end

  def get_active_projects
    @active_projects = current_user.projects.active
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_category_params
    params.require(:project_category).permit(:name, :done, :deadline, :time_needed, :project_id, :context_id, :time_needed, :postponed_to)
  end
end

app/helpers/project_categories_helper.rb
module ProjectCategoriesHelper
end

app/views/project_categories/_form.html.haml
= form_for @project_category, html: { class: "form form-horizontal project_category" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@project_category[:name])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), project_categories_path, :class => 'btn btn-default'

app/views/project_categories/edit.html.haml
- model_class = ProjectCategory
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/project_categories/index.html.haml
- model_class = ProjectCategory
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @project_categories.each do |project_category|
      %tr
        %td= link_to project_category.name, project_category_path(project_category)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_project_category_path(project_category), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), project_category_path(project_category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_project_category_path, :class => 'btn btn-primary'

app/views/project_categories/new.html.haml
- model_class = ProjectCategory
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/project_categories/show.html.haml
- model_class = ProjectCategory
.page-header
  %h1
    .label.label-default=t '.title', :default => model_class.model_name.human.titleize
    = @project_category.name

-### render projects:
- sub_model_class = Project
.panel.panel-default
  .panel-heading
    %h3.panel-title=t '.title', :default => sub_model_class.model_name.human.pluralize.titleize
  .panel-body
    %table.table.table-striped
      %thead
        %tr
          %th= sub_model_class.human_attribute_name(:id)
          %th= sub_model_class.human_attribute_name(:name)
          %th= sub_model_class.human_attribute_name(:deadline)
          %th= sub_model_class.human_attribute_name(:created_at)
          %th=t '.actions', :default => t("helpers.actions")
      %tbody
        - @project_category.projects.each do |project|
          %tr
            %td= link_to project.id, project_path(project)
            %td= link_to project.name, project_path(project)
            %td= project.deadline.datetime_without_seconds if project.deadline.nil? == false
            %td= project.created_at.datetime_without_seconds
            %td
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(project), :class => 'btn btn-default btn-xs'
              = link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

    = link_to t('.new', :default => t("helpers.links.new")), new_project_path, :class => 'btn btn-primary'

= link_to t('.back', :default => t("helpers.links.back")), project_categories_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_project_category_path(@project_category), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), project_category_path(@project_category), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'