config/routes.rb
Rails.application.routes.draw do
  root to: 'main_page#index', :controler => "main_page"
  
  devise_for :users
  
  scope "/admin" do
    resources :users, :controller => "users"  # MUST BE under 'devise_for :users'! It lets CRUD opera
  end

  resources :tasks
  resources :contexts
  resources :projects
  resources :project_categories
  resources :project_log_entries

  get 'tasks/:id/toggle_done' => 'tasks#toggle_done'

end

app/models/context.rb
class Context < ActiveRecord::Base
  belongs_to :users

  has_many :tasks

  extend SoftDeletableStatic
  include SoftDeletable
end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  #load_and_authorize_resource
  before_action :set_context_id
  before_action :set_context_service
  before_action :set_context, only: [:show, :edit]

  def index
    @contexts = @context_service.get_active_contexts_of(current_user)
  end

  def show
  end

  def new
    @context = Context.new
  end

  def edit
  end

  def create
    context_form = ContextForm.new(context_params)
    respond_to do |format|
      if @context_service.create(context_form, current_user)
        format.html { redirect_to contexts_url, notice: 'Context was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    context_form = ContextForm.new(context_params)
    respond_to do |format|
      if @context_service.update(@context_id, context_form, current_user)
        format.html { redirect_to contexts_url, notice: 'Context was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    ###Soft delete:
    @context_service.soft_delete(@context_id, current_user)
    respond_to do |format|
      format.html { redirect_to contexts_url, notice: 'Context was successfully destroyed.' }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.

  def set_context_service
    @context_service = ContextService.new
  end

  def set_context_id
    @context_id = params[:id]
  end

  def set_context
    @context = @context_service.get_context_by_id(@context_id, current_user)
    raise ActionController::RoutingError.new('Given Context is null') if @context.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def context_params
    params.require(:context).permit(:name, :color, :icon)
  end
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/views/contexts/_form.html.haml
= form_for @context, html: { class: "form form-horizontal context" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@context[:name])
  .form-group
    = f.label :color, class: 'control-label'
    .controls
      = f.text_field :color, class: 'form-control'
    = error_span(@context[:color])
  .form-group
    = f.label :icon, class: 'control-label'
    .controls
      = f.text_field :icon, class: 'form-control'
    = error_span(@context[:icon])



  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), contexts_path, :class => 'btn btn-default'

app/views/contexts/edit.html.haml
- model_class = ::Context
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/contexts/index.html.haml
- model_class = ::Context
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:color)
      %th= model_class.human_attribute_name(:icon)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @contexts.each do |context|
      %tr
        %td
          %a.context-label{style: "background-color: #{context.color}", :href => context_path(context) }
            %span{class: "glyphicon glyphicon-#{context.icon}"}
            = context.name
        %td= context.color
        %td= context.icon
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_context_path(context), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), context_path(context), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_context_path, :class => 'btn btn-primary'

app/views/contexts/new.html.haml
- model_class = ::Context
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/contexts/show.html.haml
- model_class = ::Context
.page-header
  %h1
    .context-title{style: "background-color: #{@context.color}"}
      %span{class: "glyphicon glyphicon-#{@context.icon}"}
      = @context.name

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @context.name

%p
  %strong= model_class.human_attribute_name(:color) + ':'
  %br
  = @context.color

%p
  %strong= model_class.human_attribute_name(:icon) + ':'
  %br
  = @context.icon

-### render tasks:
- sub_model_class = Task

.panel.panel-default
  .panel-heading
    %h3.panel-title=t '.title', :default => sub_model_class.model_name.human.pluralize.titleize
  .panel-body
    %table.table.table-striped
      %thead
        %tr
          %th= sub_model_class.human_attribute_name(:done)
          %th= sub_model_class.human_attribute_name(:name)
          %th= sub_model_class.human_attribute_name(:deadline)
          %th= sub_model_class.human_attribute_name(:project)
          %th= sub_model_class.human_attribute_name(:time_needed)
          %th= sub_model_class.human_attribute_name(:postponed_to)
          %th= sub_model_class.human_attribute_name(:created_at)
          %th=t '.actions', :default => t("helpers.actions")
      %tbody
        - @context.tasks.order(:done).order(:deadline).each do |task|
          %tr.task-row{:class => ('success done' if task.done)}
            %td.done-check
              %a{:href => "#", :data => {'task-id' => task.id, 'task-done' => task.done.to_s } }
                -if task.done == true
                  %span{:class => "glyphicon glyphicon-ok"}
                -else
                  %span{:class => "glyphicon glyphicon-screenshot"}
            %td= link_to task.name, task_path(task)
            %td= task.deadline
            %td= link_to(task.project.name, project_path(task.project)) if task.project.nil? == false
            %td= task.time_needed
            %td= task.postponed_to.datetime_without_seconds if task.postponed_to.nil? == false
            %td= task.created_at.datetime_without_seconds
            %td
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(task), :class => 'btn btn-default btn-xs'
              = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(task), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
    = link_to t('.new', :default => t("helpers.links.new")), new_task_path, :class => 'btn btn-primary'


= link_to t('.back', :default => t("helpers.links.back")), contexts_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_context_path(@context), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), context_path(@context), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'